### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by Random-Penguin** [PabloMK7/CTGP7ProximityChatClient#3]
Alright, so hear me out:

I used to play on Nintendo Switch Online, and there was an app on my phone that allowed me to use voice chat in certain games. Sure, it wasn't the best, but it was pretty cool.

Now I imagine that not everyone will have their computer on hand, but most people will have their phone. So I am asking you to add support for Android, for me and others left without a PC.

I don't know how writing Android apps work, neither how ShaderLab is programmed, so if I were to help, it would take a while for me to make a worthwile change/addition. I wish I could help right now, but I can't.

Please consider my suggestion, and have a good day.

**Comment by Random-Penguin** [comment]
Also maybe add a "Suggestion" label or something, to not confuse with actual issues.

**Comment by PabloMK7** [comment]
Since this is unity it's only a matter of doing an Android build. Not sure if networking stuff will work correctly tho

**Comment by Random-Penguin** [comment]
It works fine for me! Thanks!
